#!/bin/bash

. .shore/scripts/host/fn.sh

include_files

HOOK_NAME=$2
ORIGIN_DIR_PATH=$1
shift 2

docker exec -it $CONTAINER_ID_INITIALIZED /home/$PROJECT_NAME/.shore/scripts/container/_play_hook $ORIGIN_DIR_PATH $HOOK_NAME $@
