#!/bin/bash

. .shore/scripts/host/fn.sh

include_files

if [[ $CONTAINER_ID_STARTED ]]; then

  echo "$CONTAINER_ID_STARTED seems already started"

else

  printf "starting container\n\n"

  #Set container-side start script as entrypoint
  rm .shore/scripts/container/entrypoint
  ln -s _start .shore/scripts/container/entrypoint
  
  if [ -d "$PROJECT_HTDOCS" ]; then 
  
    #Docker start
    OUT=$(docker start $CONTAINER_ID_INITIALIZED 2>&1)

    if [[ $OUT =~ ^[0-9a-f]+$ ]]; then

      printf "container $OUT started\n\n"

      # Persist CONTAINER_ID_STARTED variable
      echo "CONTAINER_ID_STARTED=\"$OUT\"" > .shore/runtime/CONTAINER_ID_STARTED.var.sh

      # Start services by running the "start" container-side script
      printf "starting services ...\n\n"
      docker exec -it $CONTAINER_ID_INITIALIZED /home/$PROJECT_NAME/.shore/scripts/container/start $@
      printf "\nstarting services done\n\n"

      # Display web page URL and open browser
      printf "open the web page : http://$CONTAINER_IP/$PROJECT_NAME\n\n"
      if which xdg-open > /dev/null && [ "$OPEN_BROWSER_ON_START" = true ]; then
        xdg-open "http://$CONTAINER_IP/$PROJECT_NAME"
      fi

    else
      printf "someting went wrong:\n"
      printf "$OUT\n"
    fi
  else
    echo "web directory \"$PROJECT_HTDOCS\" doesn't exist"
  fi
fi
