#!/bin/bash

# This script is a part of Shore
# MIT License
# Copyright (c) 2016 Sylvain LAVIELLE


. "$(dirname "$0")/_common.sh"

include_files

HOOK="$2"
ORIGIN_DIR_PATH="$1"
shift 2
run_hook $HOOK $ORIGIN_DIR_PATH $@
