#!/bin/bash

# This script is a part of Shore
# MIT License
# Copyright (c) 2016 Sylvain LAVIELLE


. "$(dirname "$0")/_common.sh"

include_files

# Change current directory to project home
cd $CONF_PROJECT_CONTAINER_SIDE_PATH

# start console
/bin/bash
