#!/bin/bash

# This script is a part of Shore
# MIT License
# Copyright (c) 2016 Sylvain LAVIELLE


. "$(dirname "$0")/_common.sh"

include_files

# Start services
for SERVICE in ${CONF_SERVICES_TO_START[@]}; do
  /etc/init.d/"$SERVICE" stop
done

run_hook "stop" $@

