#!/bin/bash

# This script is a part of Shore
# MIT License
# Copyright (c) 2016 Sylvain LAVIELLE
#
# Install composer

. $(dirname "$0")/../../_common.sh

include_files


# Install Curl if need.
which curl > /dev/null
if [ "$?" == "1" ]; then
    echo "Must install curl to fulfill this operation"
    echo $(write_log_start_section "Install Curl") >> $(get_log_file_path)
    apt-get install -y curl >>$(get_log_file_path) 2>&1
    echo $(write_log_end_section "Install Curl") >> $(get_log_file_path)
fi

# Get located in var/tmp
cd /var/tmp

# Get the composer setup and check it using SHA key
echo "Install Composer"
echo $(write_log_start_section "Get Composer setup script") >> $(get_log_file_path)
php $(dirname "$0")/install.php $CONF_COMPOSER_SHA_KEY >>$(get_log_file_path) 2>&1
echo $(write_log_end_section "Get Composer setup script") >> $(get_log_file_path)


if [ -f composer-setup.php ];then
    
    # Run composer setup
    echo $(write_log_start_section "Run Composer setup") >> $(get_log_file_path)
    php composer-setup.php >>$(get_log_file_path) 2>&1
    rm composer-setup.php
    echo $(write_log_end_section "Run Composer setup") >> $(get_log_file_path)

    
    # Move and rename it in order to be able to execute it anywhere
    mv composer.phar /usr/local/bin/composer
fi

# Trace out the composer installed version
INSTALLED_VERSION=$(composer -V 2>/dev/null)
echo "Installed composer version: $INSTALLED_VERSION "

# Perform composer install.
if [ "$CONF_COMPOSER_COMPOSER_JSON_PATH" ]; then
    if [ -f "/home/$CONF_PROJECT_NAME/$CONF_COMPOSER_COMPOSER_JSON_PATH/composer.json" ]; then
        echo "Perform a \"composer install\" using \"/home/$CONF_PROJECT_NAME/$CONF_COMPOSER_COMPOSER_JSON_PATH/composer.json\"."
        cd "/home/$CONF_PROJECT_NAME/$CONF_COMPOSER_COMPOSER_JSON_PATH"
        echo $(write_log_start_section "Run \"composer install\"") >> $(get_log_file_path)
        composer install >>$(get_log_file_path) 2>&1
        echo $(write_log_end_section "Run \"composer install\"") >> $(get_log_file_path)
    else
        echo "Can't perform a \"composer install\" using \"/home/$CONF_PROJECT_NAME/$CONF_COMPOSER_COMPOSER_JSON_PATH/composer.json\". File not found"
    fi
fi

echo "Complete log at $(get_log_file_path)"
echo "Done"

