#!/bin/bash

# This script is a part of Shore
# MIT License
# Copyright (c) 2016 Sylvain LAVIELLE


. $(dirname "$0")/../../_common.sh

include_files


# Check variables.
[ -z "$CONF_NODE_VERSION" ] && echo "CONF_NODE_VERSION is not set" && exit

# curl or wget requiered
CURL_PATH=$(which curl)
WGET_PATH=$(which wget)
if [[ ! $CURL_PATH ]] && [[ ! $WGET_PATH ]]; then
    apt-get install -y curl &> /dev/null
fi


# Npm installation.
echo "Install npm" 
apt-get install -y npm &> /dev/null


# n installation.
echo "Install n"
npm cache clean -f &> /dev/null
npm install -g n &> /dev/null


# Node installation.
echo "Install node (version $CONF_NODE_VERSION)"
n "$CONF_NODE_VERSION" &> /dev/null
INSTALLED_VERSION=$(node -v)
echo "Installed node version: $INSTALLED_VERSION "

# Global node modules installation
if [[ $CONF_NODE_INSTALL_GLOBAL ]]; then
    for MODULE_NAME in $CONF_NODE_INSTALL_GLOBAL; do
        echo "Install node module \"$MODULE_NAME\" globally"
        npm install -g "$MODULE_NAME" &> /dev/null
    done
fi

# Perform npm install.
if [ "$CONF_NODE_PACKAGE_JSON_DIR" ]; then
    if [ -f "/home/$CONF_PROJECT_NAME/$CONF_NODE_PACKAGE_JSON_DIR/package.json" ]; then
        echo "Perform a \"npm install\" using \"/home/$CONF_PROJECT_NAME/$CONF_NODE_PACKAGE_JSON_DIR/package.json\"."
        cd "/home/$CONF_PROJECT_NAME/$CONF_NODE_PACKAGE_JSON_DIR"
        npm install &> /dev/null
    else
        echo "Can't perform a \"npm install\" using \"/home/$CONF_PROJECT_NAME/$CONF_NODE_PACKAGE_JSON_DIR/package.json\". File not found"
    fi
fi

