#!/bin/bash

# This script is a part of Shore
# MIT License
# Copyright (c) 2016 Sylvain LAVIELLE


. $(dirname "$0")/../../_common.sh

include_files

# Check variables.
[ -z "$CONF_NODE_VERSION" ] && echo "CONF_NODE_VERSION is not set" && exit 1
[ -z "$CONF_NODE_NODE_REPO_URL" ] && echo "$CONF_NODE_NODE_REPO_URL is not set" && exit 1

# Declare suitable node repository
curl -sL "$CONF_NODE_NODE_REPO_URL" | sudo -E bash - >>$(get_log_file_path) 2>&1

# Npm installation.
echo "Install npm"
echo $(write_log_start_section "Install npm") >> $(get_log_file_path)
apt-get install -y nodejs >>$(get_log_file_path) 2>&1
echo $(write_log_end_section "Install npm") >> $(get_log_file_path)

# n installation.
echo "Install n"
echo $(write_log_start_section "Install n") >> $(get_log_file_path)
npm cache clean -f >>$(get_log_file_path) 2>&1
npm install -g n >>$(get_log_file_path) 2>&1
echo $(write_log_end_section "Install n") >> $(get_log_file_path)

# Node installation.
echo "Install node (version $CONF_NODE_VERSION)"
echo $(write_log_start_section "Install node") >> $(get_log_file_path)
n "$CONF_NODE_VERSION" >>$(get_log_file_path) 2>&1
echo $(write_log_end_section "Install node") >> $(get_log_file_path)
INSTALLED_VERSION=$(node -v)
echo "Installed node version: $INSTALLED_VERSION"

# Global node modules installation.
if [[ $CONF_NODE_INSTALL_GLOBAL ]]; then
    for MODULE_NAME in ${CONF_NODE_INSTALL_GLOBAL[@]}; do
        echo "Install node module \"$MODULE_NAME\" globally"
        echo $(write_log_start_section "Install node module \"$MODULE_NAME\" globally") >> $(get_log_file_path)
        npm install -g "$MODULE_NAME" >>$(get_log_file_path) 2>&1
        echo $(write_log_end_section "Install node module \"$MODULE_NAME\" globally") >> $(get_log_file_path)
    done
fi

# Execute "npm install" if need.
if [ "$CONF_NODE_PACKAGE_JSON_DIR" ]; then
    if [ -f "$CONF_PROJECT_CONTAINER_SIDE_PATH/$CONF_NODE_PACKAGE_JSON_DIR/package.json" ]; then
        echo "Perform a \"npm install\" using \"$CONF_PROJECT_CONTAINER_SIDE_PATH/$CONF_NODE_PACKAGE_JSON_DIR/package.json\"."
        cd "$CONF_PROJECT_CONTAINER_SIDE_PATH/$CONF_NODE_PACKAGE_JSON_DIR"
        echo $(write_log_start_section "Perform npm install") >> $(get_log_file_path)
        npm install >>$(get_log_file_path) 2>&1
        echo $(write_log_end_section "Perform npm install") >> $(get_log_file_path)
    else
        echo "Can't perform a \"npm install\" using \"$CONF_PROJECT_CONTAINER_SIDE_PATH/$CONF_NODE_PACKAGE_JSON_DIR/package.json\". File not found"
    fi
fi

echo "Complete log at $(get_log_file_path)"
echo "Done"

