#CONTAINER_IP="172.18.0.2"
#CONTAINER_NETWORK="shore_net"
#IMAGE_ID="5bd76cc40897"
#OPEN_BROWSER_ON_START=true

#PROJECT_NAME="shore_test"
#PROJECT_HTDOCS="www"
#PROJECT_DOMAIN_NAME="shore-test.local"

#MYSQL_ROOT_PASSWORD="RoOtPas5"
MYSQL_PROJECT_USER_NAME="shore_test"
MYSQL_PROJECT_DB_NAME="shore_test"
MYSQL_PROJECT_USER_PASSWORD="shore_tes7_pa5s"

SERVICES_TO_START=("apache2" "mysql")

