#!/bin/bash

#remove first argument
COMMAND=$1
shift
if [ -f ".dockerhut/scripts/host/$COMMAND" ]; then

  echo "$COMMAND"
  ".dockerhut/scripts/host/$COMMAND" $@
else
  if [ -n "$COMMAND" ]; then
    if [ "$COMMAND" == "install" ]; then
      "$(dirname "$(readlink -f "$0")")/$COMMAND"
    else    
      echo "dockerhut: command \"$COMMAND\" not available"
    fi
  else
    echo "dockerhut: no command provided"
  fi
fi
