#!/bin/bash

. "$(dirname "$0")/resources/fn.sh"

include_files

echo "getting git project"
cd "$(dirname "$0")"/../container_workspace
git init
git remote add origin "$GIT_URL"
git pull origin master
