#!/bin/bash

# This script is a part of Shore
# MIT License
# Copyright (c) 2016 Sylvain LAVIELLE


if [ -d .shore ]; then
    echo "shore seems already installed: .shore directory exists"
else
    mkdir .shore
    cp -r "$(dirname "$0")/delivery/." .shore/.

    if test "$(ls -A .shore/runtime 2> /dev/null)"; then
        for F in .shore/runtime/*.sh; do
            . $F
        done
    fi

    mkdir .shore/runtime
    mkdir .shore/tmp
    mkdir .shore/project

    # Create main setting file
    if [ -f .shore/settings.sh ]; then
        rm .shore/settings.example.sh	
    else
        mv .shore/settings.example.sh .shore/settings.sh
    fi

    # Create bundle settings file
    for BUNDLE_SETTING_FILES in .shore/bundles/*/settings.example.sh; do
        mv "$BUNDLE_SETTING_FILES" "$(dirname "$BUNDLE_SETTING_FILES")/settings.sh"
    done

    # Remove any symlink pointing to the current project path (avoid duplicates).
    # It wouldn't append on normal use but avoid glitches while developing.
    if [ -d /var/tmp/shore/installed ]; then
        if test "$(ls -A /var/tmp/shore/installed 2> /dev/null)"; then
            for F in /var/tmp/shore/installed/*; do
                if [ "$(readlink -- "$F")" == $(pwd) ]; then
                    rm $F
                fi
            done
        fi
    fi

    # Create symlink to project directory in "installed" directory
    mkdir -p /var/tmp/shore/installed
    ln -s "$(pwd)" /var/tmp/shore/installed/"$(date +"%Y_%m_%d_%H_%M_%S")"

    #Create RT_PROFILE variable
    echo "RT_PROFILE=\"default\"" > ".shore/runtime/RT_PROFILE.var.sh"

    # Output Shore installed message
    echo ""
    echo " ###   #   #    ###    ####    ####"
    echo "#      #   #   #   #   #   #   #   "
    echo " ##    #####   #   #   ####    ### "
    echo "   #   #   #   #   #   #   #   #   "
    echo "###    #   #    ###    #   #   ####"
    echo ""
    echo "Initialized. Please follow next steps:"

    # Run post install scripts
    .shore/scripts/host/_display_change_profile_info
    .shore/scripts/host/_display_settings_info
    .shore/scripts/host/_display_run_up_info

    # And we're done
    echo ""
fi
