#!/bin/bash

. "$(dirname "$0")/resources/fn.sh"

include_files

if [[ $CONTAINER_ID_INITIALIZED ]]; then
  echo "container already initialized : $CONTAINER_ID_INITIALIZED"
else

  echo "initializing container"

  rm "$(dirname "$0")"/../docker_container/dockerhut/entrypoint 2> /dev/null
  ln -s void "$(dirname "$0")"/../docker_container/dockerhut/entrypoint

  PROJECT_DIR="$( cd "$( dirname "$0" )"/.. && pwd )"

  OUT=$(docker run -it -v $PROJECT_DIR/docker_container:/home/$PROJECT_NAME --cidfile="$(dirname "$0")"/tmp/cid --net $CONTAINER_NETWORK --ip $CONTAINER_IP $IMAGE_ID /home/$PROJECT_NAME/dockerhut/entrypoint 2>&1)
  CIDOUT=$(cat "$(dirname "$0")/tmp/cid")
  rm "$(dirname "$0")/tmp/cid"
  if [[ $CIDOUT =~ ^[0-9a-f]+$ ]]; then
    echo "container $CIDOUT initialized"
    echo "CONTAINER_ID_INITIALIZED=\"$CIDOUT\"" > "$(dirname "$0")/runtime/CONTAINER_ID_INITIALIZED.var.sh"

    echo "getting git project"
    cd "$(dirname "$0")"/../docker_container
    git init
    git remote add origin "$GIT_URL"
    git pull origin master

  else
    echo "someting went wrong:"
    echo "$OUT"
  fi
fi
