#!/bin/bash

# This script is a part of Shore
# MIT License
# Copyright (c) 2016 Sylvain LAVIELLE


if [ -d .shore ]; then
    echo "shore seems already installed: .shore directory exists"
else
    mkdir .shore
    cp -r "$(dirname "$0")/delivery/." .shore/.

    if test "$(ls -A .shore/runtime 2> /dev/null)"; then
        for F in .shore/runtime/*.sh; do
            . $F
        done
    fi

    mkdir .shore/runtime
    mkdir .shore/tmp
    mkdir .shore/project

    if [ -f .shore/settings.sh ]; then
        rm .shore/settings.example.sh	
    else
        mv .shore/settings.example.sh .shore/settings.sh
    fi
    for BUNDLE_SETTING_FILES in .shore/bundles/*/settings.example.sh; do
        mv "$BUNDLE_SETTING_FILES" "$(dirname "$BUNDLE_SETTING_FILES")/settings.sh"
    done

    echo ""
    echo " ###   #   #    ###    ####    ####"
    echo "#      #   #   #   #   #   #   #   "
    echo " ##    #####   #   #   ####    ### "
    echo "   #   #   #   #   #   #   #   #   "
    echo "###    #   #    ###    #   #   ####"
    echo ""
    echo "installed"

    .shore/scripts/host/_post_install

    echo ""
fi
