#!/bin/bash


if [ -d .shore ]; then
  echo "shore seems already installed: .shore directory exists"
else
  mkdir .shore
  cp -r "$(dirname "$0")/delivery/." .shore/.

  if test "$(ls -A .shore/runtime 2> /dev/null)"; then
    for F in .shore/runtime/*.sh; do
       . $F
    done
  fi

  if [[ $DOCKERHUT_INSTALLED ]]; then
    echo "Shore seems already installed"
  else
    mkdir .shore/runtime
    mkdir .shore/tmp
    if [ -f .shore/settings.sh ]; then
      rm .shore/settings.example.sh	
    else
      mv .shore/settings.example.sh .shore/settings.sh
    fi
  fi

  echo "shore installed"  
fi
