#!/bin/bash


if [ -d .shore ]; then
  echo "shore seems already installed: .shore directory exists"
else
  mkdir .shore
  cp -r "$(dirname "$0")/installable/." .shore/.

  if test "$(ls -A .shore/runtime 2> /dev/null)"; then
    for F in .shore/runtime/*.sh; do
       . $F
    done
  fi

  if [[ $DOCKERHUT_INSTALLED ]]; then
    echo "Shore seems already installed"
  else
    mkdir .shore/runtime
    mkdir .shore/tmp
    mv .shore/settings/container_settings.example.sh .shore/settings/container_settings.sh
    mv .shore/settings/host_settings.example.sh .shore/settings/host_settings.sh
  fi

  echo "shore installed"  
fi
