#!/bin/bash

# This script is a part of Shore
# MIT License
# Copyright (c) 2016 Sylvain LAVIELLE

ORIGIN_DIR_PATH=$1

for LINK in /var/tmp/shore/installed/*; do
    [ -d "$LINK" ] || break
    cd "$LINK"
    unset RT_CONTAINER_ID_STARTED
    . .shore/runtime/RT_CONTAINER_ID_STARTED.var.sh 2> /dev/null
    . .shore/settings.sh 2> /dev/null

    # Display web page URL and open browser
    [[ $CONF_PROJECT_DOMAIN_NAME ]] && WEB_URL="http://$CONF_PROJECT_DOMAIN_NAME" || WEB_URL="http://$CONF_CONTAINER_IP/$CONF_PROJECT_NAME"

    [ -z $RT_CONTAINER_ID_STARTED ] && STARTED="no" || STARTED="yes"

    echo "$CONF_PROJECT_NAME   started=$STARTED   ip=$CONF_CONTAINER_IP   path=$(realpath $LINK)    url=$WEB_URL"
done
