#!/bin/bash


# Init vars
WORKING_DIR_PATH=$(pwd)
ORIGIN_DIR_PATH=$(pwd)


# Get the command and remove first argument (command) from $@
COMMAND=$1
shift


# Walk up directory structure to find the .shore directory
# except for install command
if [ "$COMMAND" != "install" ]; then
  while [ "$WORKING_DIR_PATH" != "/" ] 
  do
    if [ -d .shore ]; then
      break
    fi
   cd ..
   WORKING_DIR_PATH=$(pwd)
 done
fi


# Invoke command
if [ "$WORKING_DIR_PATH" != "/" ]; then
  
  if [ -f ".shore/scripts/host/$COMMAND" ]; then
   
    # Normal command handling
    ".shore/scripts/host/$COMMAND" "$ORIGIN_DIR_PATH" $@

  else
    if [ -n "$COMMAND" ]; then
      if [ ${COMMAND:0:1} != "_" ]; then
        if [ "$COMMAND" == "install" ]; then

          # "install" command handling
          "$(dirname "$(readlink -f "$0")")/$COMMAND"

        else    
          if [ -f ".shore/hooks/define/on_$COMMAND.hook" ]; then

	    # Direct hook handling
	    echo "Triggering hooks"
	    ".shore/scripts/host/_play_hook" "$ORIGIN_DIR_PATH" $COMMAND $@

	  else
	  
	    # Command mismatch
	    echo "Shore: command \"$COMMAND\" not available"

          fi
        fi
      else
        echo "Command can't start with underscore"
      fi
    else
      echo "Shore: no command provided"
    fi
  fi
else
  echo "no .shore found on my way up !"
fi



cd "$ORIGIN_DIR_PATH"

