#!/bin/bash

# This script is a part of Shore
# MIT License
# Copyright (c) 2016 Sylvain LAVIELLE


# Init vars
WORKING_DIR_PATH=$(pwd)
ORIGIN_DIR_PATH=$(pwd)


# Get the command and remove first argument (command) from $@
COMMAND=$1
shift


# Walk up directory structure from  where the command had been called in order 
# to find the .shore directory, except for install command that is a special one
if [ "$COMMAND" != "install" ] && [ "$COMMAND" != "update_scripts" ] && [ "$COMMAND" != "stop-all" ]  && [ "$COMMAND" != "projects" ]; then
  while [ "$WORKING_DIR_PATH" != "/" ] 
  do
    if [ -d .shore ]; then
      break
    fi
   cd ..
   WORKING_DIR_PATH=$(pwd)
 done
fi


# Invoke command
if [ "$WORKING_DIR_PATH" != "/" ]; then

    #If command is specified
    if [ -n "$COMMAND" ]; then

        # If command does not start with "_" char
        if [ ${COMMAND:0:1} != "_" ]; then


            # Handle the special install command
            if [ "$COMMAND" == "install" ] || [ "$COMMAND" == "update_scripts" ] || [ "$COMMAND" == "stop-all" ] || [ "$COMMAND" == "projects" ]; then

                # "install" command handling
                "$(dirname "$0")/$(dirname "$(readlink "$0")")/$COMMAND" "$ORIGIN_DIR_PATH" $@

            # Handle all commands but install
            else
                    
                # Remove started container's reference.
                if [[ $COMMAND = "stop" ]]; then
                    . .shore/runtime/RT_CONTAINER_ID_STARTED.var.sh 2> /dev/null
                    rm /var/tmp/shore/started/"$RT_CONTAINER_ID_STARTED" 2> /dev/null
                fi

                # Command are processed by the "shore" command located in ".shore" 
                # directory of the projet directory. Doing this way command 
                # handling depend on the shore version in your project directory.
                ".shore/shore" "$ORIGIN_DIR_PATH" $COMMAND $@

                # Register started container's reference.
                if [[ $COMMAND = "start" ]]; then
                    . .shore/runtime/RT_CONTAINER_ID_STARTED.var.sh
                    mkdir -p /var/tmp/shore/started
                    ln -s "$(pwd)" /var/tmp/shore/started/"$RT_CONTAINER_ID_STARTED"
                fi

            fi
        else
            echo "Command can't start with underscore"
        fi

    #No command specified
    else
        echo "Shore: no command provided"
    fi

else
  echo "No Shore context found. The command you're invoking need to be called from inside a directory where Shore had been installed."
fi

cd "$ORIGIN_DIR_PATH"

