#!/bin/bash


# Init vars
WORKING_DIR_PATH=$(pwd)
ORIGIN_DIR_PATH=$(pwd)


# Get the command and remove first argument (command)
COMMAND=$1
shift


# Walk up directory structure to find the .shore directory
# except for install command
if [ "$COMMAND" != "install" ]; then
  echo "$WORKING_DIR_PATH"
  while [ "$WORKING_DIR_PATH" != "/" ] 
  do
    echo "test : $WORKING_DIR_PATH/.shore"
    if [ -d .shore ]; then
      break
    fi
   cd ..
   WORKING_DIR_PATH=$(pwd)
 done
fi


# Invoke command
if [ "$WORKING_DIR_PATH" != "/" ]; then
  if [ -f ".shore/scripts/host/$COMMAND" ]; then

    echo "$COMMAND"
    ".shore/scripts/host/$COMMAND" $@
  else
    if [ -n "$COMMAND" ]; then
      if [ "$COMMAND" == "install" ]; then
        "$(dirname "$(readlink -f "$0")")/$COMMAND"
      else    
        echo "shore: command \"$COMMAND\" not available"
      fi
    else
      echo "shore: no command provided"
    fi
  fi
else
  echo "no .shore found on my way up !"
fi



cd "$ORIGIN_DIR_PATH"

