#!/bin/bash

. "$(dirname "$0")/settings/settings.sh"
. "$(dirname "$0")/settings/shared_settings.sh"

if test "$(ls -A "$(dirname "$0")/runtime")"; then
  for F in "$(dirname "$0")"/runtime/*.sh; do
     . $F
  done
fi

if [[ $CONTAINER_ID_STARTED ]]; then
  echo "$CONTAINER_ID_STARTED seems already started"
else

  echo "starting container"

  rm "$(dirname "$0")"/../docker_container/dockerhut/entrypoint
  ln -s start "$(dirname "$0")"/../docker_container/dockerhut/entrypoint


  OUT=$(docker start $CONTAINER_ID_INITIALIZED 2>&1)
  if [[ $OUT =~ ^[0-9a-f]+$ ]]; then
    echo "container $OUT started"
    echo "CONTAINER_ID_STARTED=\"$OUT\"" > "$(dirname "$0")/runtime/CONTAINER_ID_STARTED.var.sh"
  
    #Start services by running the container script
    echo "starting services : "
    docker exec -it $CONTAINER_ID_INITIALIZED /home/$PROJECT_NAME/dockerhut/start_services
  else
    echo "someting went wrong:"
    echo "$OUT"
  fi
fi
