#!/bin/bash

# This script is a part of Shore
# MIT License
# Copyright (c) 2016 Sylvain LAVIELLE


. .shore/scripts/host/_common.sh

include_files

echo ""
echo "Shore is currently configured with the \"$RT_PROFILE\" profile"
echo "If you want to change it, use command \"shore profile [my_new_profile]\# to do so"
echo "using one of the following profile : "
echo ""

for PROFILE_DIRECTORY in .shore/profiles/* ; do
    echo "  $(basename "$PROFILE_DIRECTORY")"
done
echo ""
echo "otherwise follow the next step."
echo ""
