#!/bin/bash

# This script is a part of Shore
# MIT License
# Copyright (c) 2016 Sylvain LAVIELLE


. .shore/scripts/host/_common.sh

include_files

echo ""; format_output " > CREATE YOUR PROJECT CONTAINER " "step" "\n"
echo ""
echo "Run the \"shore up\" command to create the project container and install bundles."