#!/bin/bash

# This script is a part of Shore
# MIT License
# Copyright (c) 2016 Sylvain LAVIELLE


. .shore/scripts/host/_common.sh

include_files

echo ""; format_output " > UPDATE SETTINGS " "step" "\n"
echo ""
echo "Update following settings files before running \"shore up\" :"
echo "  - main settings file :"
echo "    .shore/settings.sh"
echo "  - bundles settings files used for active profile \"$RT_PROFILE\":"

# list enabled bundles settings file
while read BUNDLE || [[ -n "$BUNDLE" ]]; do

    # Trim
    if [[ "$BUNDLE" =~ ^[[:space:]]*([^[:space:]].*[^[:space:]])[[:space:]]*$ ]]; then 
        BUNDLE=${BASH_REMATCH[1]}
    fi

    # Print bundle settings file if bundle name match
    if [[ $BUNDLE =~ ^([0-9a-z_]+)$ ]]; then
        if [ -f .shore/bundles/$BUNDLE/settings.sh ]; then
            echo "    .shore/bundles/$BUNDLE/settings.sh"
        fi

    # Raise an error if not matching and line does not start with a comment char ('#')
    elif [[ $BUNDLE != \#* ]] && [ ! -z "$BUNDLE" ] ; then
        echo ""; format_output " > MISMATCH : \"$BUNDLE\" in \".shore/profiles/$RT_PROFILE/bundles\" " "error" "\n"
    fi
done <.shore/profiles/$RT_PROFILE/bundles
