#!/bin/bash

# This script is a part of Shore
# MIT License
# Copyright (c) 2016 Sylvain LAVIELLE


. .shore/scripts/host/_common.sh

include_files

HOOK_NAME=$2
ORIGIN_DIR_PATH=$1
shift 2

docker exec -it $RT_CONTAINER_ID_INITIALIZED /home/$CONF_PROJECT_NAME/.shore/scripts/container/_play_hook $ORIGIN_DIR_PATH $HOOK_NAME $@
