#!/bin/bash

# This script is a part of Shore
# MIT License
# Copyright (c) 2016 Sylvain LAVIELLE


. .shore/scripts/host/_common.sh

include_files

shift

DETACH=false
if [[ "$(uname)" == "Darwin" ]]; then
    LOG_AS_USER=$(stat -f %Su .shore)
else
    LOG_AS_USER=$(stat -c %U .shore)
fi

# Parse options.
while [[ $# -gt 0 ]]; do
    case $1 in

        -d|--detach)
            DETACH=true
            shift # past argument
        ;;

        -r|--root)
            LOG_AS_USER="root"
            shift # past argument
        ;;

        *)
            echo "Unknown option or argument \"$1\""
            exit 1
            # unknown option
        ;;
    esac
done

# Docker execute
if [ "$DETACH" = true ]; then
    x-terminal-emulator -e docker exec -it $RT_CONTAINER_ID_INITIALIZED /home/$CONF_PROJECT_NAME/.shore/scripts/container/bash $@
else
    docker exec -u $LOG_AS_USER -it $RT_CONTAINER_ID_INITIALIZED /home/$CONF_PROJECT_NAME/.shore/scripts/container/bash $@
fi
