#!/bin/bash

. .shore/scripts/host/_common.sh

include_files

if [[ $RT_CONTAINER_ID_INITIALIZED ]]; then
  echo "container already initialized : $RT_CONTAINER_ID_INITIALIZED"
else
  echo ""
  echo "initializing container using following settings:"
  echo ""

  # Remove the entrypoint (symlink to a real entrypoint script)
  rm ".shore/scripts/container/entrypoint" 2> /dev/null
  
  # Set the entrypoint symlink pointing to "init" script
  ln -s _init ".shore/scripts/container/entrypoint"

  # Set the PROJECT_DIR : project root that will be sared with container
  PROJECT_DIR="$( pwd )"

  printf "  > project directory: "; if [ "$PROJECT_DIR" ]; then printf "$PROJECT_DIR\n"; else printf "<not-set>\n"; fi
  printf "  > network: "; if [ "$CONF_CONTAINER_NETWORK" ]; then printf "$CONF_CONTAINER_NETWORK\n"; else printf "<not-set>\n"; fi
  printf "  > project name: "; if [ "$CONF_PROJECT_NAME" ]; then printf "$CONF_PROJECT_NAME\n"; else printf "<not-set>\n"; fi
  printf "  > container IP: "; if [ "$CONF_CONTAINER_IP" ]; then printf "$CONF_CONTAINER_IP\n"; else printf "<not-set>\n"; fi
  printf "  > image ID: "; if [ "$CONF_IMAGE_ID" ]; then printf "$CONF_IMAGE_ID\n"; else printf "<not-set>\n"; fi
  echo ""

  if [ "$PROJECT_DIR" ] && [ "$CONF_CONTAINER_NETWORK" ] && [ "$CONF_PROJECT_NAME" ] && [ "$CONF_CONTAINER_IP" ] && [ "$CONF_IMAGE_ID" ]; then
    # Call the docker run to create the container
    OUT=$(docker run -it -e CONF_MYSQL_ROOT_PASSWORD="$MYSQL_ROOT_PW" -v $PROJECT_DIR:/home/$CONF_PROJECT_NAME --cidfile=".shore/tmp/cid" --net $CONF_CONTAINER_NETWORK --ip $CONF_CONTAINER_IP $CONF_IMAGE_ID /home/$CONF_PROJECT_NAME/.shore/scripts/container/entrypoint 2>&1)

    # Get the run's container ID
    CIDOUT=$(cat ".shore/tmp/cid" 2> /dev/null)
    rm ".shore/tmp/cid" 2> /dev/null

    if [[ $CIDOUT =~ ^[0-9a-f]+$ ]]; then
    
      # Report message on success
      echo "container $CIDOUT initialized"

      # Store runtime variables
      echo "RT_CONTAINER_ID_INITIALIZED=\"$CIDOUT\"" > ".shore/runtime/RT_CONTAINER_ID_INITIALIZED.var.sh"
      echo "RT_HOST_SHARED_DIR_PATH=\"$PROJECT_DIR\"" > ".shore/runtime/RT_HOST_SHARED_DIR_PATH.var.sh"

      # Set container-side "_start" script as entrypoint
      rm .shore/scripts/container/entrypoint
      ln -s _start .shore/scripts/container/entrypoint

      # Start the container
      docker start $CIDOUT > /dev/null

      # Execute the container "init" script
      docker exec -it $CIDOUT /home/$CONF_PROJECT_NAME/.shore/scripts/container/init $@
      
      # Stop the container
      docker stop $CIDOUT > /dev/null

    else
    
      # Report message on error 
      echo "Oops, someting went wrong:"
      echo "$OUT"
  
    fi
  else
    echo "Some expected settings are not defined. Please edit files in .shore/settings to set setting values"
  fi
fi
