#!/bin/bash

# This script is a part of Shore
# MIT License
# Copyright (c) 2016 Sylvain LAVIELLE


. .shore/scripts/host/_common.sh

include_files

docker exec -it $RT_CONTAINER_ID_INITIALIZED mysql -u root -p"$CONF_MYSQL_ROOT_PASSWORD"
