#!/bin/bash

# This script is a part of Shore
# MIT License
# Copyright (c) 2016 Sylvain LAVIELLE


. .shore/scripts/host/_common.sh

include_files

echo ""

if [ -z "$2" ]; then
    echo "Current profile:"
    echo "  $RT_PROFILE"
    echo "Available profiles:"
    for PROFILE_DIRECTORY in .shore/profiles/* ; do
        echo "  $(basename "$PROFILE_DIRECTORY")"
    done

else
    FOUND=false
    for PROFILE_DIRECTORY in .shore/profiles/* ; do
        if [ $1 = "$(basename "$PROFILE_DIRECTORY")" ]; then
            FOUND=true
        fi
    done

    if [ FOUND ]; then
        echo "RT_PROFILE=\"$2\"" > ".shore/runtime/RT_PROFILE.var.sh"
        echo "New profile \"$2\" is set. Please follow next steps:"
        .shore/scripts/host/_display_settings_info
        .shore/scripts/host/_display_run_init_info
    else
        echo "Profile \"$2\" doesn't exist."
    fi
fi

echo ""