#!/bin/bash

. .shore/scripts/host/_common.sh

include_files

if [[ $CONTAINER_ID_STARTED ]]; then

  #Stop services by running the "stop" container script
  echo "stopping services : "

  docker exec -it $CONTAINER_ID_STARTED /home/$CONF_PROJECT_NAME/.shore/scripts/container/stop $@

  echo "stopping container"
  docker stop $CONTAINER_ID_STARTED
  echo "$CONTAINER_ID_STARTED stopped"
  rm .shore/runtime/CONTAINER_ID_STARTED.var.sh
else
  echo "$CONTAINER_ID_INITIALIZED seems not to be started or hadn't been stopped properly"
fi
