#!/bin/bash

# This script is a part of Shore
# MIT License
# Copyright (c) 2016 Sylvain LAVIELLE


. .shore/scripts/host/_common.sh

include_files

if [[ $RT_CONTAINER_ID_STARTED ]]; then
    
    # Test if container is running
    TEST_CONTAINER_RUNNING=$(docker ps -q --filter ID="$RT_CONTAINER_ID_STARTED")

    if [ -n "$TEST_CONTAINER_RUNNING" ] && [[ $RT_CONTAINER_ID_STARTED = $TEST_CONTAINER_RUNNING* ]]; then

        # Stop services by running the "stop" container-side script
        echo "Stopping services : "
        docker exec -it $RT_CONTAINER_ID_STARTED /home/$CONF_PROJECT_NAME/.shore/scripts/container/stop $@

        # Stop container itself
        echo "Stopping container"
        VOID=$(docker stop $RT_CONTAINER_ID_STARTED)
        echo "$RT_CONTAINER_ID_STARTED stopped"

    else
        echo "Someting went wrong:"
        echo "Container wasn't running"
    fi

    #Drop runtime variable
    rm .shore/runtime/RT_CONTAINER_ID_STARTED.var.sh
  
else
    echo "$RT_CONTAINER_ID_INITIALIZED seems not to be started or hadn't been stopped properly"
fi
