#!/bin/bash

# This script is a part of Shore
# MIT License
# Copyright (c) 2016 Sylvain LAVIELLE


. .shore/scripts/host/_common.sh

include_files

if [ -f .shore/VERSION.txt ]; then
    cat .shore/VERSION.txt
else
    echo "No version specified"
fi