#!/bin/bash

. "$(dirname "$0")/../settings/container_settings.sh"

# Start services
for SERVICE in ${SERVICES_TO_START[@]}; do
  /etc/init.d/"$SERVICE" start
done

# Create symbolic link in Apache web directory
if [ ! -e "/var/www/html/$PROJECT_NAME" ]; then
    ln -s "/home/$PROJECT_NAME/$PROJECT_HTDOCS" "/var/www/html/$PROJECT_NAME"
fi

