#!/bin/bash

# This script is a part of Shore
# MIT License
# Copyright (c) 2016 Sylvain LAVIELLE
#
# Create the symlink and vhost for project.

. $(dirname "$0")/../../_common.sh

include_files

# Get user id from .shore directory on container side
if [[ "$(uname)" == "Darwin" ]]; then
    USER_ID=$(stat -f '%u' /home/$CONF_PROJECT_NAME/.shore)
else
    USER_ID=$(stat -c '%u' /home/$CONF_PROJECT_NAME/.shore)
fi

# Create the corresponding user form host side to container side.
useradd -u $USER_ID $RT_INIT_USER

