#!/bin/bash

# This script is a part of Shore
# MIT License
# Copyright (c) 2016 Sylvain LAVIELLE
#
# Create the symlink and vhost for project.

. $(dirname "$0")/../../_common.sh

include_files

# Get user id from .shore directory on container side
if [[ "$(uname)" == "Darwin" ]]; then
    USER_ID=$(stat -f '%u' /home/$CONF_PROJECT_NAME/.shore)
else
    USER_ID=$(stat -c '%u' /home/$CONF_PROJECT_NAME/.shore)
fi

# Create the corresponding user form host side to container side.
if [[ "$RT_HOST_UNAME" == "Darwin" ]]; then

    # MacOS platform case : Create user without specific ID
    useradd $RT_INIT_USER
else

    # Others (Ubuntu tested) Create user container side corresponding to host 
    # side user
    useradd -u $USER_ID $RT_INIT_USER
fi

echo "\"$RT_INIT_USER\" user created container side."
echo "Done"