#!/bin/bash

# This script is a part of Shore
# MIT License
# Copyright (c) 2016 Sylvain LAVIELLE


. $(dirname "$0")/../../_common.sh

include_files

#"root" "$RT_USER_NAME"

PASS="$(pwgen -s 12 1)"
echo "root:$PASS" | chpasswd
echo "RT_ROOT_PASSWORD=\"$PASS\"" > "$(get_runtime_dir_path)/RT_ROOT_PASSWORD.var.sh"
echo "\"root\" user pasword's reset."

PASS="$(pwgen -s 12 1)"
echo "$RT_USER_NAME:$PASS" | chpasswd
echo "RT_USER_PASSWORD=\"$PASS\"" > "$(get_runtime_dir_path)/RT_USER_PASSWORD.var.sh"
echo "\"$RT_USER_NAME\" user pasword's reset."