#!/bin/bash

. "$(dirname "$0")/fn.sh"
. "$(dirname "$0")/../../settings/container_settings.sh"

# Start services
for SERVICE in ${SERVICES_TO_START[@]}; do
  /etc/init.d/"$SERVICE" start
done

run_hook "start"


