#!/bin/bash

# Create the symlink and vhost for project

. $(dirname "$0")/_common.sh

include_files


# Create symlink in Apache web directory
if [ ! -e "/var/www/html/$PROJECT_NAME" ]; then
  ln -s "/home/$PROJECT_NAME/$PROJECT_HTDOCS" "/var/www/html/$PROJECT_NAME"  
fi


# Create vhost in /etc/apache2/sites-available
cat >/etc/apache2/sites-available/"$PROJECT_NAME".conf <<EOL
<Directory /var/www/html/${PROJECT_NAME}>
        Options Indexes FollowSymLinks
        AllowOverride All
</Directory>
<VirtualHost *:80>
        ServerName ${PROJECT_DOMAIN_NAME}
        DocumentRoot /var/www/html/${PROJECT_NAME}
        ErrorLog \${APACHE_LOG_DIR}/error.log
        CustomLog \${APACHE_LOG_DIR}/access.log combined
</VirtualHost>
EOL


# Create the symlink in /etc/apache2/sites-available
ln -s /etc/apache2/sites-available/"$PROJECT_NAME".conf /etc/apache2/sites-enabled/"$PROJECT_NAME".conf

echo "Done"
