#PROJECT_NAME="shore_test"
#PROJECT_HTDOCS="www"
#PROJECT_DOMAIN_NAME="shore-test.local"
#MYSQL_ROOT_PASSWORD="RoOtPas5"
MYSQL_PROJECT_USER_NAME="shore_test"
MYSQL_PROJECT_DB_NAME="shore_test"
MYSQL_PROJECT_USER_PASSWORD="shore_tes7_pa5s"
SERVICES_TO_START=("apache2" "mysql")
