#!/bin/bash

. "$(dirname "$0")/settings.sh"

# Start Apache and MySql
/etc/init.d/apache2 start
/etc/init.d/mysql start

# Create symbolic link in Apache web directory
if [ ! -e "/var/www/html/$PROJECT_NAME" ]; then
    ln -s "/home/$PROJECT_NAME/$PROJECT_HTDOCS" "/var/www/html/$PROJECT_NAME"
fi

