#!/bin/bash

# This script is a part of Shore
# MIT License
# Copyright (c) 2016 Sylvain LAVIELLE


. $(dirname "$0")/../../_common.sh

include_files


# Install XDebug.
echo "Installing XDebug" 
apt-get install -y php5-xdebug &> /dev/null


# Set config.
echo "Setting up XDebug config"
CONF=$(cat /etc/php5/apache2/conf.d/20-xdebug.ini)
cat >/etc/php5/apache2/conf.d/20-xdebug.ini <<EOL
$CONF
xdebug.remote_enable=1
xdebug.remote_handler=dbgp
xdebug.remote_mode=req
xdebug.remote_host=$CONF_HOST_IP
xdebug.remote_port=9000
EOL