#!/bin/bash

# This script is a part of Shore
# MIT License
# Copyright (c) 2016 Sylvain LAVIELLE


. .shore/scripts/host/_common.sh

include_files

# Parse options.
shift
DETACH=false
while [[ $# -gt 0 ]]; do
    case $1 in

        -d|--detach)
            DETACH=true
            shift # past argument
        ;;

        *)
            # unknown option
        ;;
    esac
    shift # past argument or value
done

#Checking before executing
[ -z "$RT_CONTAINER_ID_INITIALIZED" ] && echo "Container seems not initialized" && exit

if [ "$DETACH" = true ]; then
    x-terminal-emulator -e docker exec -it $RT_CONTAINER_ID_INITIALIZED tail -fn 20 /var/log/apache2/error.log
else
    docker exec -it $RT_CONTAINER_ID_INITIALIZED tail -fn 20 /var/log/apache2/error.log
fi

