#!/bin/bash

# This script is a part of Shore
# MIT License
# Copyright (c) 2016 Sylvain LAVIELLE


# install php5 and 

. $(dirname "$0")/../../_common.sh

include_files

# Install PHP5
echo "Install PHP5"
echo $(write_log_start_section "Install PHP5") >> $(get_log_file_path)
apt-get -y install php5 >>$(get_log_file_path) 2>&1
echo $(write_log_end_section "Install PHP5") >> $(get_log_file_path)

# Install PHP5 libs
if [[ $CONF_PHP5_LIBS ]]; then
    for LIB in ${CONF_PHP5_LIBS[@]}; do
        echo "Install PHP5 lib \"$LIB\""
        echo $(write_log_start_section "Install PHP5 lib \"$LIB\"") >> $(get_log_file_path)
            apt-get install -y $LIB >>$(get_log_file_path) 2>&1
        echo $(write_log_end_section "Install PHP5 lib \"$LIB\"") >> $(get_log_file_path)
    done
fi

echo "Complete log at $(get_log_file_path)"
echo "Done"