#!/bin/bash

# This script is a part of Shore
# MIT License
# Copyright (c) 2016 Sylvain LAVIELLE


# Create project user and database.

. $(dirname "$0")/../../_common.sh

include_files


# Check variables.
[ -z "$CONF_MYSQL_ROOT_PASSWORD" ] && echo "CONF_MYSQL_ROOT_PASSWORD is not set" && exit
[ -z "$CONF_MYSQL_PROJECT_DB_NAME" ] && echo "CONF_MYSQL_PROJECT_DB_NAME is not set" && exit
[ -z "$CONF_MYSQL_PROJECT_USER_NAME" ] && echo "CONF_MYSQL_PROJECT_USER_NAME is not set" && exit
[ -z "$CONF_MYSQL_PROJECT_USER_PASSWORD" ] && echo "CONF_MYSQL_PROJECT_USER_PASSWORD is not set" && exit


# Start MySql if need.
if [[ -z $(pgrep mysql) ]]; then
  echo "MySQL have to be started to perform this hook ... starting"
  service mysql start
fi


# Drop existing project user if any and recreate it.
mysql -u root -p"$CONF_MYSQL_ROOT_PASSWORD" -e "DROP USER $CONF_MYSQL_PROJECT_USER_NAME@$CONF_CONTAINER_IP;" &> /dev/null
mysql -u root -p"$CONF_MYSQL_ROOT_PASSWORD" -e "DROP USER $CONF_MYSQL_PROJECT_USER_NAME@localhost;" &> /dev/null


# Drop project database and recreate it.
echo "Create project database & project database user"
mysql -u root -p"$CONF_MYSQL_ROOT_PASSWORD" -e "DROP DATABASE IF EXISTS $CONF_MYSQL_PROJECT_DB_NAME; CREATE DATABASE $CONF_MYSQL_PROJECT_DB_NAME DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;" &> /dev/null
mysql -u root -p"$CONF_MYSQL_ROOT_PASSWORD" -e "GRANT ALL PRIVILEGES ON $CONF_MYSQL_PROJECT_USER_NAME.* TO '$CONF_MYSQL_PROJECT_DB_NAME'@'$CONF_CONTAINER_IP' IDENTIFIED BY '$CONF_MYSQL_PROJECT_USER_PASSWORD'" &> /dev/null
mysql -u root -p"$CONF_MYSQL_ROOT_PASSWORD" -e "GRANT ALL PRIVILEGES ON $CONF_MYSQL_PROJECT_USER_NAME.* TO '$CONF_MYSQL_PROJECT_DB_NAME'@'localhost' IDENTIFIED BY '$CONF_MYSQL_PROJECT_USER_PASSWORD'" &> /dev/null
echo ""
echo "Done"
