#!/bin/bash

# This script is a part of Shore
# MIT License
# Copyright (c) 2016 Sylvain LAVIELLE
#
# Create a mysql root user that can be logged in remotely from host.


. $(dirname "$0")/../../_common.sh

include_files


# Check variables.
[ -z "$CONF_MYSQL_ROOT_PASSWORD" ] && echo "CONF_MYSQL_ROOT_PASSWORD is not set" && exit


# Start MySql if need.
if [[ -z $(pgrep mysql) ]]; then
  echo "MySQL have to be started to perform this hook ... starting"
  service mysql start
fi


# Drop existing project user if any and recreate it.
echo "Create root user for  $RT_HOST_IP"
echo $(write_log_start_section "Create root user") >> $(get_log_file_path)
QUERY="DROP USER root@$RT_HOST_IP;"
mysql -u root -p"$CONF_MYSQL_ROOT_PASSWORD" -e "$QUERY" >>$(get_log_file_path) 2>&1
QUERY="CREATE USER 'root'@'$RT_HOST_IP' IDENTIFIED BY '$CONF_MYSQL_ROOT_PASSWORD';"
mysql -u root -p"$CONF_MYSQL_ROOT_PASSWORD" -e "$QUERY" >>$(get_log_file_path) 2>&1
QUERY="GRANT ALL PRIVILEGES ON *.* TO 'root'@'$RT_HOST_IP';"
mysql -u root -p"$CONF_MYSQL_ROOT_PASSWORD" -e "$QUERY" >>$(get_log_file_path) 2>&1
echo $(write_log_end_section "Create root user") >> $(get_log_file_path)

echo ""
echo "Complete log at $(get_log_file_path)"
echo "Done"