#!/bin/bash

. $(dirname "$0")/../../_common.sh

include_files

IMPORT_FILE_PATH="$1/$2"
FILE_FORMAT_HANDLED=false

if [ -f $IMPORT_FILE_PATH ]; then
  if [[ $IMPORT_FILE_PATH =~ \.sql$ ]]; then
    FILE_FORMAT_HANDLED=true
    mysql -u "$CONF_MYSQL_PROJECT_USER_NAME" -p"$CONF_MYSQL_PROJECT_USER_PASSWORD" "$CONF_MYSQL_PROJECT_DB_NAME" < "$IMPORT_FILE_PATH"
    echo "$1/$2 imported"
fi

  if ! $FILE_FORMAT_HANDLED; then
    echo "Unknown file format: \"$IMPORT_FILE_PATH\". Import failed"
  fi

else
  echo "No such file \"$IMPORT_FILE_PATH\". Import failed"

fi



