#!/bin/bash

# This script is a part of Shore
# MIT License
# Copyright (c) 2016 Sylvain LAVIELLE


. $(dirname "$0")/../../_common.sh

include_files


# Check variables.
[ -z "$CONF_MYSQL_PROJECT_DB_NAME" ] && echo "CONF_MYSQL_PROJECT_DB_NAME is not set" && exit
[ -z "$CONF_MYSQL_PROJECT_USER_NAME" ] && echo "CONF_MYSQL_PROJECT_USER_NAME is not set" && exit
[ -z "$CONF_MYSQL_PROJECT_USER_PASSWORD" ] && echo "CONF_MYSQL_PROJECT_USER_PASSWORD is not set" && exit


IMPORT_FILE_PATH="$1/$2"
FILE_FORMAT_HANDLED=false

#Import file.
if [ -f $IMPORT_FILE_PATH ]; then
    
    # Import .sql file.
    if [[ $IMPORT_FILE_PATH =~ \.sql$ ]] || [[ $IMPORT_FILE_PATH =~ \.mysql$ ]]; then
        FILE_FORMAT_HANDLED=true
        echo $(write_log_start_section "Import database") >> $(get_log_file_path)
        mysql -u "$CONF_MYSQL_PROJECT_USER_NAME" -p"$CONF_MYSQL_PROJECT_USER_PASSWORD" "$CONF_MYSQL_PROJECT_DB_NAME" < "$IMPORT_FILE_PATH" >>$(get_log_file_path) 2>&1
        echo $(write_log_end_section "Import database") >> $(get_log_file_path)
        echo "$1/$2 imported"
        echo "Complete log at $(get_log_file_path)"
    fi

    # @todo other formats (.gz .zip) to be implemented later.

    if ! $FILE_FORMAT_HANDLED; then
        echo "Unknown file format: \"$IMPORT_FILE_PATH\". Import failed."
    else
        echo "File imported."
    fi

else
  echo "No such file \"$IMPORT_FILE_PATH\". Import failed."
fi



