#!/bin/bash

# This script is a part of Shore
# MIT License
# Copyright (c) 2016 Sylvain LAVIELLE


# Set MySQL root pass

. $(dirname "$0")/../../_common.sh

include_files


# Check variables.
[ -z "$CONF_MYSQL_ROOT_PASSWORD" ] && echo "CONF_MYSQL_ROOT_PASSWORD is not set" && exit


# Start MySql.
if [ -z $(pgrep -l mysqld) ]; then
    echo "MySQL have to be started to perform this hook ... starting"
    echo $(write_log_start_section "Starting MySql") >> $(get_log_file_path)
    service mysql start >>$(get_log_file_path) 2>&1
    echo $(write_log_end_section "Starting MySql") >> $(get_log_file_path)
    echo ""
fi

#Change root password.
echo $(write_log_start_section "Change root password") >> $(get_log_file_path)
mysqladmin -u root password "$CONF_MYSQL_ROOT_PASSWORD" >>$(get_log_file_path) 2>&1
echo $(write_log_end_section "Change root password") >> $(get_log_file_path)


echo "Complete log at $(get_log_file_path)"
echo "Done"
