#!/bin/bash

# This script is a part of Shore
# MIT License
# Copyright (c) 2016 Sylvain LAVIELLE


# Set MySQL root pass

. $(dirname "$0")/../../_common.sh

include_files


# Check variables.
[ -z "$CONF_MYSQL_ROOT_PASSWORD" ] && echo "CONF_MYSQL_ROOT_PASSWORD is not set" && exit


# Start MySql.
if [ -z $(pgrep -l mysqld) ]; then
  echo "MySQL have to be started to perform this hook ... starting"
  service mysql start
  echo ""
fi

#Change root password.
mysqladmin -u root password "$CONF_MYSQL_ROOT_PASSWORD"

echo "Done"
