#!/bin/bash

# This script is a part of Shore
# MIT License
# Copyright (c) 2016 Sylvain LAVIELLE


# Create the symlink and vhost for project.

. $(dirname "$0")/../../_common.sh

include_files

# Install MySQL
echo "Install MySQL"
apt-get -y install mysql-server &> /dev/null

