#!/bin/bash

# This script is a part of Shore
# MIT License
# Copyright (c) 2016 Sylvain LAVIELLE


# Create the symlink and vhost for project.

. $(dirname "$0")/../../_common.sh

include_files

# Install MySQL
echo "Install MySQL"
echo $(write_log_start_section "Install MySQL") >> $(get_log_file_path)
apt-get -y install mysql-server >>$(get_log_file_path) 2>&1
echo $(write_log_end_section "Install MySQL") >> $(get_log_file_path)

echo "Complete log at $(get_log_file_path)"
echo "Done"

