CONF_CONTAINER_IP="172.18.0.2"
CONF_HOST_IP="172.18.0.1"
#CONF_CONTAINER_NETWORK="shore_net"
#CONF_IMAGE_ID="5bd76cc40897"
CONF_OPEN_BROWSER_ON_START=true
CONF_SERVICES_TO_START=("apache2" "mysql")

#CONF_PROJECT_NAME="shore_test"
#CONF_PROJECT_HTDOCS="www"
#CONF_PROJECT_DOMAIN_NAME="shore-test.local"

#CONF_MYSQL_ROOT_PASSWORD="RoOtPas5"
CONF_MYSQL_PROJECT_USER_NAME="shore_test"
CONF_MYSQL_PROJECT_DB_NAME="shore_test"
CONF_MYSQL_PROJECT_USER_PASSWORD="shore_tes7_pa5s"

CONF_DRUSH_VERSION="8.1.3"

CONF_NODE_VERSION="lts"

