CONTAINER_IP="172.18.0.2"
HOST_IP="172.18.0.1"
#CONTAINER_NETWORK="shore_net"
#IMAGE_ID="5bd76cc40897"
OPEN_BROWSER_ON_START=true
SERVICES_TO_START=("apache2" "mysql")

#PROJECT_NAME="shore_test"
#PROJECT_HTDOCS="www"
#PROJECT_DOMAIN_NAME="shore-test.local"

#MYSQL_ROOT_PASSWORD="RoOtPas5"
MYSQL_PROJECT_USER_NAME="shore_test"
MYSQL_PROJECT_DB_NAME="shore_test"
MYSQL_PROJECT_USER_PASSWORD="shore_tes7_pa5s"

DRUSH_VERSION="8.1.3"

