CONF_CONTAINER_IP="172.18.0.2"
CONF_HOST_IP="172.18.0.1"
CONF_CONTAINER_NETWORK="shore_net"
CONF_IMAGE_ID="debian:jessie"
CONF_OPEN_BROWSER_ON_START=true
CONF_SERVICES_TO_START=("apache2" "mysql")

#CONF_PROJECT_NAME="shore_test"
#CONF_PROJECT_HTDOCS="www"
#CONF_PROJECT_DOMAIN_NAME="shore-test.local"
